# define paths to libraries in use
LIBRARIES	:= ../../../lib/uc_includes
# enable framebuffer in the 16FXlib (requires recompilation of the library!)
#MACROS		:= -D ENABLE_FRAMEBUFFER
# include main makefile
include ../../../c.mk
