# define paths to libraries in use
LIBRARIES	:= ../../../lib/uc_includes
# example to include both libraries
#LIBRARIES	:= ../../../lib/uc_includes ../../../lib/16FXlib
# include main makefile
include ../../../c.mk
